epochs: 10000
batch_size: 2
num_workers: 1
wandb: False
wandb_project: Graphafold
checkpoint_dir: checkpoints
data:
  train_dir: prep_data
  val_dir: my_val
model:
  in_feats: 512
  hidden_feats: 256
  hidden_dim: 384
  edge_feats: 2
  gcn_layers: 2