epochs: 100
batch_size: 128
num_workers: 1
wandb: False
wandb_project: Graphafold
checkpoint_dir: checkpoints
data:
  train_dir: train_prep # train_prep
  val_dir: train_exp # prep_data
  sampling_mode: range # alllowed: 'all', 'range'
  sampling_range: 10 # sampling range around known canonical base pairs.
model:
  hidden_feats: 32
  edge_feats: 2
  gcn_layers: 2