epochs: 1000
batch_size: 64
num_workers: 1
wandb: True
wandb_project: Graphafold
checkpoint_dir: checkpoints
data:
  train_dir: train_prep
  val_dir: prep_data # prep_data
model:
  in_feats: 512
  hidden_feats: 64
  hidden_dim: 384
  edge_feats: 2
  gcn_layers: 2